-- Query to identify execution activities mapped to GOODS_SERVICES event
-- This shows all execution activities that are mapped to the GOODS_SERVICES event code

SELECT 
  da.id AS activity_id,
  da.name AS activity_name,
  da.project_type,
  da.facility_type,
  sac.code AS category_code,
  sac.sub_category_code,
  cem.mapping_type,
  cem.mapping_ratio,
  cem.is_active,
  cem.metadata->>'fallbackMapping' AS is_fallback_mapping,
  cem.metadata->>'autoGenerated' AS is_auto_generated,
  cem.created_at,
  cem.updated_at
FROM configurable_event_mappings cem
JOIN dynamic_activities da ON cem.activity_id = da.id
JOIN events e ON cem.event_id = e.id
JOIN schema_activity_categories sac ON da.category_id = sac.id
WHERE 
  e.code = 'GOODS_SERVICES'
  AND da.module_type = 'execution'
  AND cem.is_active = true
ORDER BY 
  da.project_type,
  da.facility_type,
  sac.code,
  da.name;

-- Summary statistics by project type
SELECT 
  da.project_type,
  COUNT(*) AS total_goods_services_mappings,
  COUNT(*) FILTER (WHERE cem.metadata->>'fallbackMapping' = 'true') AS fallback_mappings,
  COUNT(*) FILTER (WHERE cem.metadata->>'fallbackMapping' IS NULL OR cem.metadata->>'fallbackMapping' = 'false') AS explicit_mappings
FROM configurable_event_mappings cem
JOIN dynamic_activities da ON cem.activity_id = da.id
JOIN events e ON cem.event_id = e.id
WHERE 
  e.code = 'GOODS_SERVICES'
  AND da.module_type = 'execution'
  AND cem.is_active = true
GROUP BY da.project_type
ORDER BY da.project_type;

-- Check for any B-category activities NOT mapped to GOODS_SERVICES
-- (These might be explicitly mapped to other events)
-- B-category codes follow pattern: HIV_EXEC_B, HIV_EXEC_B-01, MAL_EXEC_B-02, etc.
SELECT 
  da.id AS activity_id,
  da.name AS activity_name,
  da.project_type,
  da.facility_type,
  sac.code AS category_code,
  e.code AS mapped_to_event,
  cem.metadata->>'activityName' AS explicit_mapping_name
FROM dynamic_activities da
JOIN schema_activity_categories sac ON da.category_id = sac.id
LEFT JOIN configurable_event_mappings cem ON da.id = cem.activity_id AND cem.is_active = true
LEFT JOIN events e ON cem.event_id = e.id
WHERE 
  da.module_type = 'execution'
  AND da.is_total_row = false
  AND (sac.code LIKE '%_B-%' OR sac.code LIKE '%_B')
  AND (e.code IS NULL OR e.code != 'GOODS_SERVICES')
ORDER BY 
  da.project_type,
  da.name;
